# Generated by Django 2.1.7 on 2019-04-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='site',
        ),
    ]
