# Generated by Django 2.1.7 on 2019-04-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distros', '0002_auto_20190405_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_updates',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site_tags',
        ),
    ]
