# Generated by Django 2.1.7 on 2019-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distros', '0006_auto_20190415_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.FloatField(),
        ),
    ]
