# Generated by Django 2.1.7 on 2019-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distros', '0008_auto_20190415_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
