# Generated by Django 2.1.7 on 2019-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distros', '0009_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
